clear

% 男甲: ['地空','化学','环科','生科','数学','外院','医学','元培'],
% 男乙: ['叉院','电子','法学','工学','光华','国发','国关','集电','计算机','教历','经济','马院','软微','社会','物理','心理','新城','信管','信科','艺哲','政管','智能','中文'],
% 女甲: ['化学','外院','新传','信管','信科','医学','元培','中文'],
% 女乙: ['城环','地空','法学','光经','国关','教育','马院','软微','社会','生历','数学','物理','心理','艺哲','政管']
% team_new = {};
team_new = {...
    '甲1' 'm' '环科' ... % 男甲: ['地空','化学','环科','生科','数学','外院','医学','元培'],
    '甲2' 'm' '数学' ...
    '甲3' 'm' '外院' ...
    '甲4' 'm' '地空' ...
    '甲5' 'm' '元培' ...
    '甲6' 'm' '医学' ...
    '甲7' 'm' '生科' ...
    '甲8' 'm' '化学' ...
    ...
    'A1' 'm' '物理' ... % 男乙: ['叉院','电子','法学','工学','光华','国发','国关','集电','计算机','教历','经济','马院','软微','社会','物理','心理','新城','信管','信科','艺哲','政管','智能','中文'],
    'A2' 'm' '新城' ...
    'A3' 'm' '马院' ...
    'A4' 'm' '法学' ...
    'B1' 'm' '光华' ... 
    'B2' 'm' '教历' ...
    'B3' 'm' '信管' ...
    'B4' 'm' '电子' ...
    'C1' 'm' '软微' ...
    'C2' 'm' '国关' ...
    'C3' 'm' '智能' ...
    'C4' 'm' '叉院' ...
    'D1' 'm' '心理' ...
    'D2' 'm' '中文' ...
    'D3' 'm' '国发' ...
    'D4' 'm' '经济' ... 
    'E1' 'm' '工学' ...
    'E2' 'm' '社会' ...
    'E3' 'm' '集电' ...
    'E4' 'm' '计算机' ...
    'F1' 'm' '信科' ...
    'F2' 'm' '艺哲' ...
    'F3' 'm' '政管' ...
    ...
    '甲1' 'f' '外院' ... % 女甲: ['化学','外院','新传','信管','信科','医学','元培','中文'],
    '甲2' 'f' '元培' ...
    '甲3' 'f' '信管' ...
    '甲4' 'f' '信科' ...
    '甲5' 'f' '医学' ...
    '甲6' 'f' '新传' ...
    '甲7' 'f' '化学' ...
    '甲8' 'f' '中文' ...
    ...
    'A1' 'f' '社会' ... % 女乙: ['城环','地空','法学','光经','国关','教育','马院','软微','社会','生历','数学','物理','心理','艺哲','政管']
    'A2' 'f' '生历' ...
    'A3' 'f' '数学' ...
    'A4' 'f' '地空' ...
    'A5' 'f' '光经' ...
    'B1' 'f' '教育' ...
    'B2' 'f' '政管' ...
    'B3' 'f' '马院' ...
    'B4' 'f' '心理' ...
    'B5' 'f' '城环' ...
    'C1' 'f' '国关' ...
    'C2' 'f' '艺哲' ...
    'C3' 'f' '法学' ...
    'C4' 'f' '软微' ...
    'C5' 'f' '物理' ...
    };
meta = ['{' ...
        '"games": ["男甲","男乙","女甲","女乙"],' ... % 应与app.js中GROUP_NAMES相同
        '"place_all": ["五四东一","五四东二","五四东三","邱德拔"]' ... 
        '}' ];
% fid = fopen('meta.json');
% meta = fread(fid)';
% meta = native2unicode(meta);
meta = jsondecode(meta);
% fclose(fid);

% 规定表中每一列所使用的场地
place_all = meta.place_all;
place_num = length(place_all);
place = cell(place_num,1);
place{1} = [2,5,8,12,14,17];
place{2} = [3,6,9,13,15];
place{3}= [4,7,10];
place{4} = [11,16];



[~,txt,data] = xlsread('schedule.xlsx');

[row,col] = size(data);
data_new = [];
for k = 1:row
    for j = 1:col
        if strfind(upper(data{k,j}),'VS')
            temp = data{k,j};
            temp(temp==' ')=''; % delete all space
            tempdata.sex = true;
            if temp(end-1) == '女'
                tempdata.sex = false;
                if strcmp(temp(1),'甲')
                    tempdata.group = meta.games{3};
                else
                    tempdata.group = meta.games{4};
                end
                pos_end = 3;
            else
                tempdata.sex = true;
                if strcmp(temp(1),'甲')
                    tempdata.group = meta.games{1};
                else
                    tempdata.group = meta.games{2};
                end
                pos_end = 0;
            end
            if strfind(data{k,j},'VS')
                pos1 = strfind(data{k,j},'VS')-1;
            elseif strfind(data{k,j},'vs')
                pos1 = strfind(data{k,j},'vs')-1;
            end
            pos2 = pos1 + 3;
            tempdata.home_team = temp(1:pos1);
            tempdata.away_team = temp(pos2:end-pos_end);
            tempdata.home_team_score = -1;
            tempdata.away_team_score = -1;
            % substitute
            for i = 1:3:length(team_new)
                if strcmp(tempdata.home_team,team_new{i}) && (tempdata.sex == (strcmp(team_new{i+1},'m')))
                    tempdata.home_team = team_new{i+2};
                elseif strcmp(tempdata.home_team,team_new{i}) && (tempdata.sex == (~strcmp(team_new{i+1},'f')))
                    tempdata.home_team = team_new{i+2};                    
                end
                if strcmp(tempdata.away_team,team_new{i}) && (tempdata.sex == (strcmp(team_new{i+1},'m')))
                    tempdata.away_team = team_new{i+2};
                elseif strcmp(tempdata.away_team,team_new{i}) && (tempdata.sex == (~strcmp(team_new{i+1},'f')))
                    tempdata.away_team = team_new{i+2};                    
                end
            end
            for i = 1:place_num
                if sum(place{i}==j)>=1
                    tempdata.place = place_all{i};
                    break
                end
            end
            if contains([tempdata.home_team,tempdata.away_team],'决赛') && ~contains([tempdata.home_team,tempdata.away_team],'半决赛')
                tempdata.adjustable = false;
            else
                tempdata.adjustable = true;
            end
            temp_time = datetime([datestr(data{k,1},'yyyy/mm/dd'),datestr(data{1,j},' HH:MM:00')]);
            temp_time = temp_time - hours(8); %微信小程序数据库导入时区为+0，中国为+8
            tempdata0 = jsonencode(tempdata);
            tempdata0 = [tempdata0(1:end-1),',"time":{"$date":"',datestr(temp_time,'yyyy-mm-ddTHH:MM:00Z"}}')];
            data_new = [data_new,tempdata0];
        end
    end
end
disp(data_new)
fid = fopen('schedule.json','w','n','UTF-8');
%fwrite(fid,data_new);
fprintf(fid, '%s', data_new);
fclose(fid);